// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlyJwQmyAz3T7vO6TAprnfewzKIyFd3uY',
    appId: '1:570245314355:web:1dff14818eb2edb57fb046',
    messagingSenderId: '570245314355',
    projectId: 'esiot2024-80ec9',
    authDomain: 'esiot2024-80ec9.firebaseapp.com',
    databaseURL: 'https://esiot2024-80ec9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esiot2024-80ec9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqIleFnUp_9VOxWTzCipmXJYcD1AJKg4I',
    appId: '1:570245314355:android:beb40acab9588dc07fb046',
    messagingSenderId: '570245314355',
    projectId: 'esiot2024-80ec9',
    databaseURL: 'https://esiot2024-80ec9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esiot2024-80ec9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOMLJnzIXIM24SEPcT_p3zQ9QqLsZIet4',
    appId: '1:570245314355:web:fdb5abe6309255cc7fb046',
    messagingSenderId: '570245314355',
    projectId: 'esiot2024-80ec9',
    authDomain: 'esiot2024-80ec9.firebaseapp.com',
    databaseURL: 'https://esiot2024-80ec9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esiot2024-80ec9.firebasestorage.app',
  );
}
